In [1]:
import sys
sys.path.append("../src/")

In [2]:
import pandas as pd
from sklearn.pipeline import Pipeline
from encoders.custom_transformer import CustomTransformer, MultiplyColumns

In [3]:
df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6], "c": [7, 8, 9]})

In [4]:
df

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [7]:
pipe = Pipeline(
    steps=[
        ("use_custom_transformer", CustomTransformer())
    ]
)

transformed_df = pipe.fit_transform(df)

In [8]:
transformed_df

   a  b  c  random_int
0  1  4  7           0
1  2  5  8           9
2  3  6  9           7

`pipe.fit_transform(df)` is a shorthand for `pipe.fit(df)` and `pipe.transform(df)`. Internally, this means:
- `Pipeline.fit(df)` calls `CustomTransformer.fit(df)`
- `Pipeline.transform(df)` calls `CustomTransformer.transform(df)`

It passes the data through each transformer step **in order** and returns the final transformed data.

- Each step **must implement** `fit()` and `transform()`
- `fit_transform()` is automatically handled if we inherit from `TransformerMixin`

### **What Makes a Custom Class Compatible?**
- It must inherit from `BaseEstimator` and `TransformerMixin` or at least implement `.fit(X, y=None)` and `.transform()`
- Otionally, it the last step is a model (e.g., Logistic Regression), it must implement `.fit(X, y)` and `.predict(X)` or `.predict_proba(X)`.

In [7]:
df

   a  b  c  random_int
0  1  4  7           7
1  2  5  8           3
2  3  6  9           1

In [8]:
df = pd.DataFrame({"a": [1, -2, 3], "b": [-4, 5, 6], "c": [-7, -8, 9]})

In [9]:
df

   a  b  c
0  1 -4 -7
1 -2  5 -8
2  3  6  9

In [11]:
pipe = Pipeline(
    steps=[
        ("multiply_by_3", MultiplyColumns(3, columns=["a", "c"]))
    ]
)

In [12]:
transformed_df = pipe.fit_transform(df)

In [13]:
transformed_df

   a  b   c
0  3 -4 -21
1 -6  5 -24
2  9  6  27